# Site settings
title: "CS371p Spring 2016: Tipparat Umrod"
email: tipparat.umrod[at]utexas[dot]edu
description: > # this means to ignore newlines until "baseurl:"
  Computer Science | Computational Biology
  Class of 2016 | University of Texas at Austin
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://tumrod.github.io/blog-cs371p" # the base hostname & protocol for your site
twitter_username: tipptong
github_username:  tumrod

# Build settings
markdown: kramdown